force-app/main/default/objects/Country__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Country_Code_3__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_3__c</fullName>
    <label>Country Code 3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country alpha2code</description>
    <externalId>true</externalId>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <formula>Country__r.Capital_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Capital City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Code_3__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_3__c</fullName>
    <formula>Country__r.Country_Code_3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code 3</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <formula>Country__r.Country_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadServiceTest.cls
/** 
 * Test class for LeadService and LeadTrigger
 */
@isTest
public with sharing class LeadServiceTest {

    private static final String COUNTRY_NAME = 'Switzerland';

    @TestSetup
    static void prepareData(){
        Country__c countrySwiss = new Country__c(
            Name = COUNTRY_NAME, 
            Country_Code__c = 'CH',
            Country_Code_3__c = 'CHE',
            Capital_City__c = 'Bern',
            Region__c = 'Europe'
            );
        insert countrySwiss;
    }

    @isTest
    static void updateCountryLookupTest_Negative() {
        Test.startTest();
        Lead lead = new Lead(LastName = 'LastNameTest', Company = 'Test Company');
        insert lead;
        System.assertEquals(null, [SELECT Country__c FROM Lead WHERE Id = :lead.Id].Country__c, 'Country__c should not be populated.');
        lead.Country = 'Germany';
        update lead;
        Test.stopTest();

        System.assertEquals(null, [SELECT Country__c FROM Lead WHERE Id = :lead.Id].Country__c, 'Country__c should not be populated.');
    }

    @isTest
    static void updateCountryLookupTest_Positive() {
        Test.startTest();
        // insert without Country
        Lead lead = new Lead(LastName = 'LastNameTest', Company = 'Test Company');
        insert lead;
        System.assertEquals(null, [SELECT Country__c FROM Lead WHERE Id = :lead.Id].Country__c, 'Country__c should not be populated.');

        //update Country to existing one
        lead.Country = COUNTRY_NAME;
        update lead;
        System.assertEquals(COUNTRY_NAME, [SELECT Country__r.Name FROM Lead WHERE Id = :lead.Id].Country__r?.Name, 'Country__c should be populated.');

        // insert with existing Country
        lead = new Lead(LastName = 'LastNameTest', Company = 'Test Company', Country = COUNTRY_NAME);
        insert lead;
        System.assertEquals(COUNTRY_NAME, [SELECT Country__r.Name FROM Lead WHERE Id = :lead.Id].Country__r?.Name, 'Country__c should be populated.');
        Test.stopTest();
    }
}