force-app/main/default/objects/Country__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country alpha2code</description>
    <externalId>true</externalId>
    <label>Country Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CountryApiServiceMock.cls
/**
 * Mock class for CountryApiService used in tests
 */
@isTest
public with sharing class CountryApiServiceMock implements System.StubProvider {
    public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, 
    Type returnType, List<Type> listOfParamTypes, List<String> listOfParamNames, 
    List<Object> listOfArgs) {
        List<Country__c> countries = new List<Country__c>();
        countries.add(new Country__c(Name = 'Switzerland', Country_Code__c = 'CH'));
        return countries;
    }
}